# Generated by Django 2.2.6 on 2020-03-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200308_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thum',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
    ]
